// <auto-generated />
using System;
using IMDbReplicaAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IMDbReplicaAPI.Migrations
{
    [DbContext(typeof(IMDbReplicaContext))]
    [Migration("20190603000852_InitialDbWithData")]
    partial class InitialDbWithData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IMDbReplicaAPI.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Actor");

                    b.HasData(
                        new { Id = 1, Name = "Steven Seagal" },
                        new { Id = 2, Name = "Jan Claude Van Damme" },
                        new { Id = 3, Name = "Ian Mcgregor" },
                        new { Id = 4, Name = "Brad Pitt" },
                        new { Id = 5, Name = "Leonardo Di Caprio" }
                    );
                });

            modelBuilder.Entity("IMDbReplicaAPI.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("ImageUrl");

                    b.Property<int>("MovieType");

                    b.Property<decimal>("Rating");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new { Id = 1, Description = "It's story about disney aladin.", ImageUrl = "../../assets/images/aladin.jpg", MovieType = 0, Rating = 2.4m, ReleaseDate = new DateTime(2019, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Aladin 2019" },
                        new { Id = 2, Description = "It's story about disney aladin.", ImageUrl = "../../assets/images/godzila.jpg", MovieType = 0, Rating = 2.5m, ReleaseDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Godzilla: King of the Monsters(2019)" },
                        new { Id = 3, Description = "A musical fantasy about the fantastical human story of Elton John's breakthrough years.", ImageUrl = "../../assets/images/rocketman.jpg", MovieType = 0, Rating = 3.5m, ReleaseDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Rocketman (2019)" },
                        new { Id = 4, Description = "It's story about prisoners who became good friends and try to escape", ImageUrl = "../../assets/images/shawshank.jpg", MovieType = 0, Rating = 4.9m, ReleaseDate = new DateTime(1994, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "The Shawshank Redemption (1994)" },
                        new { Id = 5, Description = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", ImageUrl = "../../assets/images/godfather.jpg", MovieType = 0, Rating = 4.9m, ReleaseDate = new DateTime(1972, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "The Godfather (1972)" },
                        new { Id = 6, Description = "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.", ImageUrl = "../../assets/images/godfather2.jpg", MovieType = 0, Rating = 4.8m, ReleaseDate = new DateTime(1974, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "The Godfather: Part II (1974)" },
                        new { Id = 7, Description = "When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.", ImageUrl = "../../assets/images/darknight.jpg", MovieType = 0, Rating = 4.2m, ReleaseDate = new DateTime(2008, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "The Dark Knight (2008)" },
                        new { Id = 8, Description = "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.", ImageUrl = "../../assets/images/angry.jpg", MovieType = 0, Rating = 3.9m, ReleaseDate = new DateTime(1957, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "12 Angry Men (1957)" },
                        new { Id = 9, Description = "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.", ImageUrl = "../../assets/images/fight.jpg", MovieType = 0, Rating = 3.8m, ReleaseDate = new DateTime(1999, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Fight Club (1999)" },
                        new { Id = 10, Description = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.", ImageUrl = "../../assets/images/lord.jpg", MovieType = 0, Rating = 3.7m, ReleaseDate = new DateTime(2003, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "The Lord of the Rings: The Return of the King (2003)" },
                        new { Id = 11, Description = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.", ImageUrl = "../../assets/images/schindler.jpg", MovieType = 0, Rating = 4.4m, ReleaseDate = new DateTime(1993, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Schindler's List (1993)" },
                        new { Id = 12, Description = "In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world's worst man-made catastrophes.", ImageUrl = "../../assets/images/chernobyl.jpg", MovieType = 1, Rating = 4.9m, ReleaseDate = new DateTime(2019, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Chernobyl (2019)" },
                        new { Id = 13, Description = "David Attenborough returns in this breathtaking documentary showcasing life on Planet Earth.", ImageUrl = "../../assets/images/planet.jpg", MovieType = 1, Rating = 4.7m, ReleaseDate = new DateTime(2016, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Planet Earth II (2016)" },
                        new { Id = 14, Description = "The story of Easy Company of the U.S. Army 101st Airborne Division, and their mission in World War II Europe, from Operation Overlord, through V-J Day.", ImageUrl = "../../assets/images/band.jpg", MovieType = 1, Rating = 4.8m, ReleaseDate = new DateTime(2001, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Band of Brothers (2001)" },
                        new { Id = 15, Description = "Emmy Award-winning, 11 episodes, five years in the making, the most expensive nature documentary series ever commissioned by the BBC, and the first to be filmed in high definition.", ImageUrl = "../../assets/images/planet1.jpg", MovieType = 1, Rating = 4.6m, ReleaseDate = new DateTime(2006, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Planet Earth (2006)" },
                        new { Id = 16, Description = "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.", ImageUrl = "../../assets/images/bad.jpg", MovieType = 1, Rating = 4.9m, ReleaseDate = new DateTime(2008, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Breaking Bad (2008)" },
                        new { Id = 17, Description = "Nine noble families fight for control over the mythical lands of Westeros, while an ancient enemy returns after being dormant for thousands of years.", ImageUrl = "../../assets/images/got.jpg", MovieType = 1, Rating = 5.0m, ReleaseDate = new DateTime(2011, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Game of Thrones (2011)" },
                        new { Id = 18, Description = "Baltimore drug scene, seen through the eyes of drug dealers and law enforcement.", ImageUrl = "../../assets/images/wire.jpg", MovieType = 1, Rating = 3.7m, ReleaseDate = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "The Wire (2002)" },
                        new { Id = 19, Description = "Documentary series focusing on the breadth of the diversity of habitats around the world, from the remote Arctic wilderness and mysterious deep oceans to the vast landscapes of Africa and diverse jungles of South America.", ImageUrl = "../../assets/images/our.jpg", MovieType = 1, Rating = 3.5m, ReleaseDate = new DateTime(2019, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Our Planet (2019)" },
                        new { Id = 20, Description = "An exploration of our discovery of the laws of nature and coordinates in space and time.", ImageUrl = "../../assets/images/cosmos.jpg", MovieType = 1, Rating = 3.1m, ReleaseDate = new DateTime(2014, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Cosmos (2014)" },
                        new { Id = 21, Description = "David Attenborough returns to the world's oceans in this sequel to the acclaimed documentary filming rare and unusual creatures of the deep, as well as documenting the problems our oceans face.", ImageUrl = "../../assets/images/blue.jpg", MovieType = 1, Rating = 3.3m, ReleaseDate = new DateTime(2017, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Blue Planet II (2017)" },
                        new { Id = 22, Description = "An animated series that follows the exploits of a super scientist and his not-so-bright grandson.", ImageUrl = "../../assets/images/rick.jpg", MovieType = 1, Rating = 2.9m, ReleaseDate = new DateTime(2013, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Rick and Morty (2013)" }
                    );
                });

            modelBuilder.Entity("IMDbReplicaAPI.Models.MovieActor", b =>
                {
                    b.Property<int>("MovieId");

                    b.Property<int>("ActorId");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActor");

                    b.HasData(
                        new { MovieId = 1, ActorId = 1 },
                        new { MovieId = 1, ActorId = 2 },
                        new { MovieId = 1, ActorId = 3 },
                        new { MovieId = 1, ActorId = 4 },
                        new { MovieId = 2, ActorId = 1 },
                        new { MovieId = 2, ActorId = 2 },
                        new { MovieId = 2, ActorId = 5 },
                        new { MovieId = 3, ActorId = 3 },
                        new { MovieId = 3, ActorId = 5 },
                        new { MovieId = 4, ActorId = 4 },
                        new { MovieId = 4, ActorId = 5 },
                        new { MovieId = 4, ActorId = 2 },
                        new { MovieId = 4, ActorId = 1 },
                        new { MovieId = 5, ActorId = 2 },
                        new { MovieId = 5, ActorId = 5 },
                        new { MovieId = 5, ActorId = 3 },
                        new { MovieId = 6, ActorId = 4 },
                        new { MovieId = 6, ActorId = 5 },
                        new { MovieId = 6, ActorId = 2 },
                        new { MovieId = 6, ActorId = 3 },
                        new { MovieId = 7, ActorId = 4 },
                        new { MovieId = 7, ActorId = 5 },
                        new { MovieId = 7, ActorId = 3 },
                        new { MovieId = 7, ActorId = 1 },
                        new { MovieId = 8, ActorId = 4 },
                        new { MovieId = 8, ActorId = 5 },
                        new { MovieId = 8, ActorId = 2 },
                        new { MovieId = 8, ActorId = 3 },
                        new { MovieId = 9, ActorId = 4 },
                        new { MovieId = 9, ActorId = 5 },
                        new { MovieId = 9, ActorId = 3 },
                        new { MovieId = 9, ActorId = 1 },
                        new { MovieId = 10, ActorId = 4 },
                        new { MovieId = 10, ActorId = 5 },
                        new { MovieId = 10, ActorId = 2 },
                        new { MovieId = 10, ActorId = 1 },
                        new { MovieId = 11, ActorId = 4 },
                        new { MovieId = 11, ActorId = 5 },
                        new { MovieId = 11, ActorId = 2 },
                        new { MovieId = 11, ActorId = 3 }
                    );
                });

            modelBuilder.Entity("IMDbReplicaAPI.Models.RatingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MovieId");

                    b.Property<int>("TotalNumberOfVotes");

                    b.Property<int>("TotalVotesRating");

                    b.HasKey("Id");

                    b.HasIndex("MovieId")
                        .IsUnique();

                    b.ToTable("RatingHistory");

                    b.HasData(
                        new { Id = 1, MovieId = 1, TotalNumberOfVotes = 100, TotalVotesRating = 240 },
                        new { Id = 2, MovieId = 2, TotalNumberOfVotes = 100, TotalVotesRating = 250 },
                        new { Id = 3, MovieId = 3, TotalNumberOfVotes = 100, TotalVotesRating = 350 },
                        new { Id = 4, MovieId = 4, TotalNumberOfVotes = 100, TotalVotesRating = 490 },
                        new { Id = 5, MovieId = 5, TotalNumberOfVotes = 100, TotalVotesRating = 490 },
                        new { Id = 6, MovieId = 6, TotalNumberOfVotes = 100, TotalVotesRating = 480 },
                        new { Id = 7, MovieId = 7, TotalNumberOfVotes = 100, TotalVotesRating = 420 },
                        new { Id = 8, MovieId = 8, TotalNumberOfVotes = 100, TotalVotesRating = 390 },
                        new { Id = 9, MovieId = 9, TotalNumberOfVotes = 100, TotalVotesRating = 380 },
                        new { Id = 10, MovieId = 10, TotalNumberOfVotes = 100, TotalVotesRating = 370 },
                        new { Id = 11, MovieId = 11, TotalNumberOfVotes = 100, TotalVotesRating = 440 },
                        new { Id = 12, MovieId = 12, TotalNumberOfVotes = 100, TotalVotesRating = 490 },
                        new { Id = 13, MovieId = 13, TotalNumberOfVotes = 100, TotalVotesRating = 470 },
                        new { Id = 14, MovieId = 14, TotalNumberOfVotes = 100, TotalVotesRating = 480 },
                        new { Id = 15, MovieId = 15, TotalNumberOfVotes = 100, TotalVotesRating = 460 },
                        new { Id = 16, MovieId = 16, TotalNumberOfVotes = 100, TotalVotesRating = 490 },
                        new { Id = 17, MovieId = 17, TotalNumberOfVotes = 100, TotalVotesRating = 500 },
                        new { Id = 18, MovieId = 18, TotalNumberOfVotes = 100, TotalVotesRating = 370 },
                        new { Id = 19, MovieId = 19, TotalNumberOfVotes = 100, TotalVotesRating = 350 },
                        new { Id = 20, MovieId = 20, TotalNumberOfVotes = 100, TotalVotesRating = 310 },
                        new { Id = 21, MovieId = 21, TotalNumberOfVotes = 100, TotalVotesRating = 330 },
                        new { Id = 22, MovieId = 22, TotalNumberOfVotes = 100, TotalVotesRating = 290 }
                    );
                });

            modelBuilder.Entity("IMDbReplicaAPI.Models.MovieActor", b =>
                {
                    b.HasOne("IMDbReplicaAPI.Models.Actor", "Actor")
                        .WithMany("Movies")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMDbReplicaAPI.Models.Movie", "Movie")
                        .WithMany("Actors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IMDbReplicaAPI.Models.RatingHistory", b =>
                {
                    b.HasOne("IMDbReplicaAPI.Models.Movie", "Movie")
                        .WithOne("RatingHistory")
                        .HasForeignKey("IMDbReplicaAPI.Models.RatingHistory", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
